#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

runApplication $application
runApplication yPlus -latestTime
runApplication wallShearStress -latestTime
runApplication sample -latestTime

# ----------------------------------------------------------------- end-of-file
