#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`

runApplication $application
runApplication yPlus -latestTime -noSlip && mv log.yPlus log.yPlus@interface
runApplication yPlus -latestTime -region ImpingedWall
runApplication wallShearStress -latestTime -region ImpingedWall
runApplication sample -latestTime -region ImpingedWall

# ----------------------------------------------------------------- end-of-file
