#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanTimeDirectories
rm -rf postProcessing > /dev/null 2>&1

# ----------------------------------------------------------------- end-of-file
